# API

## Login
POST http://localhost:9091/admin/login
Content-Type: application/json

{
    "email": "praethip-h@rmutp.ac.th", 
    "password": "120975922Aa", 
    "rememberMe": false
}

## Forgot
## Profile
## Register / Signup